name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push nodejs image
        uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          push: true
          tags: krismyid/pintu-sre-questions:nodejs

      - name: Build and push golang image
        uses: docker/build-push-action@v2
        with:
          context: ./golang
          push: true
          tags: krismyid/pintu-sre-questions:golang
