name: Release Charts

on:
  workflow_run:
    workflows: [Test and Build Docker Images]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser for Golang
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm-golan
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"